import type { NextPage } from 'next'
import axios from 'axios';
import Head from 'next/head'
import Organization from '../modules/home/components/organization'
import {useState, useEffect} from 'react'
import styles from '../styles/Home.module.css'

const axiosGitHubGraphQL = axios.create({
  baseURL: 'https://api.github.com/graphql',
  headers: {
    Authorization: `bearer ${
      process.env.NEXT_PUBLIC_GITHUB_PERSONAL_ACCESS_TOKEN
    }`,
  },
});
const TITLE = 'React GraphQL GitHub Client';
const GET_ORGANIZATION = `
  {
    organization(login: "the-road-to-learn-react") {
      name
      url
    }
  }
`;

const Home: NextPage = () => {
  const [path, setPath] = useState('the-road-to-learn-react/the-road-to-learn-react');
  const [organization, setOrganization] = useState();
  const [errors, setErrors] = useState();
  const fetchDataFromGithub = () => {
    axiosGitHubGraphQL
      .post('', { query: GET_ORGANIZATION })
      .then(result => {
        setOrganization(result.data.data.organization);
        setErrors(result.data.errors);
      });
  }

  useEffect(() => {
   fetchDataFromGithub();
  }, []);

  const inputUpdated = (e: React.ChangeEvent<HTMLInputElement>) => setPath(e.currentTarget.value);
  const submitForm = (e: React.FormEvent) => {
    e.preventDefault();
    fetchDataFromGithub();
  };
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <h1>{TITLE}</h1>
        <form onSubmit={submitForm}>
          <label htmlFor="url">
            Show open issues for https://github.com/
          </label>
          <input
            id="url"
            type="text"
            value={path}
            onChange={inputUpdated}
            autoFocus
          />
          <button type="submit">Submit</button>
        </form>

        <hr />
        { organization
          ? <Organization organization={organization} errors={errors} />
          : <p>No information yet ...</p>
        } 
      </main>
    </div>
  )
}

export default Home
